const API_NOW_PLAYING = 'API_NOW_PLAYING'
const API_LATEST = 'API_LATEST'
const API_DETAIL = 'API_DETAIL'
const FETCH_START = 'FETCH_START'
const FETCH_END = 'FETCH_END'

export default {
  API_NOW_PLAYING,
  API_LATEST,
  API_DETAIL,
  FETCH_START,
  FETCH_END,
}
