const API_NOW_PLAYING = 'API_NOW_PLAYING'
const API_LATEST = 'API_LATEST'
const API_DETAIL = 'API_DETAIL'
const FETCH_LATEST_START = 'FETCH_LATEST_START'
const FETCH_LATEST_END = 'FETCH_LATEST_END'
const FETCH_NOW_PLAYING_START = 'FETCH_NOW_PLAYING_START'
const FETCH_NOW_PLAYING_END = 'FETCH_NOW_PLAYING_END'
const FETCH_API_DETAIL_START = 'FETCH_API_DETAIL_START'
const FETCH_API_DETAIL_END = 'FETCH_API_DETAIL_END'

export default {
  API_NOW_PLAYING,
  API_LATEST,
  API_DETAIL,
  FETCH_LATEST_START,
  FETCH_LATEST_END,
  FETCH_NOW_PLAYING_START,
  FETCH_NOW_PLAYING_END,
  FETCH_API_DETAIL_START,
  FETCH_API_DETAIL_END
}
